'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import jsPDF from 'jspdf';

interface BudgetItem {
  id: string;
  category: string;
  budgeted: number;
  spent: number;
}

export default function BudgetPlanner() {
  const [budgetItems, setBudgetItems] = useState<BudgetItem[]>([]);
  const [newCategory, setNewCategory] = useState('');
  const [newBudgeted, setNewBudgeted] = useState('');

  // Load budget data from localStorage on mount
  useEffect(() => {
    const storedBudget = localStorage.getItem('budgetItems');
    if (storedBudget) {
      setBudgetItems(JSON.parse(storedBudget));
    } else {
      // Load example data if no stored budget
      loadExampleData();
    }
  }, []);

  // Save budget data to localStorage whenever it changes
  useEffect(() => {
    localStorage.setItem('budgetItems', JSON.stringify(budgetItems));
  }, [budgetItems]);

  /**
   * Loads example budget data for demonstration.
   */
  const loadExampleData = () => {
    const exampleBudget: BudgetItem[] = [
      { id: '1', category: 'Food & Dining', budgeted: 600, spent: 450 },
      { id: '2', category: 'Transportation', budgeted: 300, spent: 280 },
      { id: '3', category: 'Entertainment', budgeted: 200, spent: 150 },
      { id: '4', category: 'Utilities', budgeted: 250, spent: 220 },
      { id: '5', category: 'Shopping', budgeted: 150, spent: 120 }
    ];
    setBudgetItems(exampleBudget);
  };

  /**
   * Adds a new budget item.
   */
  const addBudgetItem = () => {
    if (!newCategory.trim() || !newBudgeted) return;

    const newItem: BudgetItem = {
      id: Date.now().toString(),
      category: newCategory.trim(),
      budgeted: parseFloat(newBudgeted),
      spent: 0
    };

    setBudgetItems(prev => [...prev, newItem]);
    setNewCategory('');
    setNewBudgeted('');
  };

  /**
   * Updates the spent amount for a budget item.
   */
  const updateSpent = (id: string, spent: number) => {
    setBudgetItems(prev =>
      prev.map(item =>
        item.id === id ? { ...item, spent } : item
      )
    );
  };

  /**
   * Deletes a budget item.
   */
  const deleteBudgetItem = (id: string) => {
    setBudgetItems(prev => prev.filter(item => item.id !== id));
  };

  /**
   * Generates and downloads a PDF report of the budget.
   */
  const generatePDF = () => {
    const doc = new jsPDF();
    const currentDate = new Date().toLocaleDateString();

    // Title
    doc.setFontSize(20);
    doc.text('Monthly Budget Report', 20, 30);

    // Date
    doc.setFontSize(12);
    doc.text(`Generated on: ${currentDate}`, 20, 45);

    // Budget Summary
    const totalBudgeted = budgetItems.reduce((sum, item) => sum + item.budgeted, 0);
    const totalSpent = budgetItems.reduce((sum, item) => sum + item.spent, 0);
    const remaining = totalBudgeted - totalSpent;

    doc.setFontSize(14);
    doc.text('Budget Summary:', 20, 65);
    doc.setFontSize(12);
    doc.text(`Total Budgeted: $${totalBudgeted.toFixed(2)}`, 20, 80);
    doc.text(`Total Spent: $${totalSpent.toFixed(2)}`, 20, 90);
    doc.text(`Remaining: $${remaining.toFixed(2)}`, 20, 100);

    // Budget Items
    doc.setFontSize(14);
    doc.text('Budget Categories:', 20, 120);

    let yPosition = 135;
    budgetItems.forEach((item, index) => {
      const remaining = item.budgeted - item.spent;
      const status = remaining >= 0 ? 'Under Budget' : 'Over Budget';

      doc.setFontSize(12);
      doc.text(`${item.category}:`, 20, yPosition);
      doc.text(`Budgeted: $${item.budgeted.toFixed(2)}`, 40, yPosition + 10);
      doc.text(`Spent: $${item.spent.toFixed(2)}`, 40, yPosition + 20);
      doc.text(`Remaining: $${remaining.toFixed(2)} (${status})`, 40, yPosition + 30);

      yPosition += 45;

      // Add new page if needed
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 30;
      }
    });

    // Footer
    doc.setFontSize(10);
    doc.text('Generated by Financial Tools Suite - Jameson A. Olitoquit', 20, 280);

    doc.save('budget-report.pdf');
  };

  const totalBudgeted = budgetItems.reduce((sum, item) => sum + item.budgeted, 0);
  const totalSpent = budgetItems.reduce((sum, item) => sum + item.spent, 0);
  const totalRemaining = totalBudgeted - totalSpent;

  return (
    <LayoutWithSidebar>
      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-gray-900 dark:to-gray-800 py-8 px-4">
        <div className="max-w-4xl mx-auto">
          <div className="mb-6">
            <Link
              href="/"
              className="inline-flex items-center text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 font-medium"
            >
              ← Back to Dashboard
            </Link>
          </div>

          <header className="text-center mb-8">
            <h1 className="text-4xl font-bold text-gray-900 dark:text-white">Budget Planner</h1>
            <p className="text-gray-800 dark:text-gray-300 mt-2 font-medium">Plan and track your monthly budget</p>
          </header>

          <div className="mb-6 flex justify-center gap-4">
            <button
              onClick={loadExampleData}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
            >
              Load Example Data
            </button>
            <button
              onClick={generatePDF}
              className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
            >
              Download PDF Report
            </button>
          </div>

          {/* Budget Summary */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg p-6 text-center">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Total Budgeted</h3>
              <p className="text-2xl font-bold text-blue-600 dark:text-blue-400">${totalBudgeted.toFixed(2)}</p>
            </div>
            <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg p-6 text-center">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Total Spent</h3>
              <p className="text-2xl font-bold text-red-600 dark:text-red-400">${totalSpent.toFixed(2)}</p>
            </div>
            <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg p-6 text-center">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Remaining</h3>
              <p className={`text-2xl font-bold ${totalRemaining >= 0 ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400'}`}>
                ${totalRemaining.toFixed(2)}
              </p>
            </div>
          </div>

          {/* Add New Budget Item */}
          <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg p-6 mb-8">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">Add Budget Category</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <input
                type="text"
                placeholder="Category name"
                value={newCategory}
                onChange={(e) => setNewCategory(e.target.value)}
                className="px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white dark:bg-gray-800 text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-500"
              />
              <input
                type="number"
                placeholder="Budgeted amount"
                value={newBudgeted}
                onChange={(e) => setNewBudgeted(e.target.value)}
                className="px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white dark:bg-gray-800 text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-500"
                min="0"
                step="0.01"
              />
              <button
                onClick={addBudgetItem}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
              >
                Add Category
              </button>
            </div>
          </div>

          {/* Budget Items List */}
          <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg p-6">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">Budget Categories</h2>
            {budgetItems.length === 0 ? (
              <p className="text-gray-600 dark:text-gray-400 text-center py-8">No budget categories added yet. Add your first category above.</p>
            ) : (
              <div className="space-y-4">
                {budgetItems.map((item) => {
                  const remaining = item.budgeted - item.spent;
                  const isOverBudget = remaining < 0;

                  return (
                    <div key={item.id} className="border border-gray-200 dark:border-gray-700 rounded-lg p-4">
                      <div className="flex justify-between items-center mb-3">
                        <h3 className="text-lg font-medium text-gray-900 dark:text-white">{item.category}</h3>
                      <button
                        onClick={() => deleteBudgetItem(item.id)}
                        className="text-red-600 hover:text-red-800 font-medium"
                      >
                        Delete
                      </button>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-3">
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Budgeted</label>
                        <p className="text-lg font-semibold text-blue-600">${item.budgeted.toFixed(2)}</p>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Spent</label>
                        <input
                          type="number"
                          value={item.spent}
                          onChange={(e) => updateSpent(item.id, parseFloat(e.target.value) || 0)}
                          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                          min="0"
                          step="0.01"
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Remaining</label>
                        <p className={`text-lg font-semibold ${isOverBudget ? 'text-red-600' : 'text-green-600'}`}>
                          ${remaining.toFixed(2)}
                        </p>
                      </div>
                    </div>

                    <div className="w-full bg-gray-200 rounded-full h-2">
                      <div
                        className={`h-2 rounded-full ${isOverBudget ? 'bg-red-500' : 'bg-green-500'}`}
                        style={{ width: `${Math.min((item.spent / item.budgeted) * 100, 100)}%` }}
                      ></div>
                    </div>
                    <p className="text-sm text-gray-600 mt-1">
                      {((item.spent / item.budgeted) * 100).toFixed(1)}% of budget used
                    </p>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}